### PR TITLE
fix download function when showOptions is false

### PR DESCRIPTION
**Pull request by r03ert0**
Hello! The download function tries to read a checkbox that only exists if showOptions had been set to true. If showOptions is false, the function fails. I added a check for showOptions and the function works now :)

### CODE REVIEW

**Comment by KTGLeiden** [comment]
Thanks for reaching out and taking the time for fixing the issue as well!

Also, thanks for using this plugin. I really hope it is of use to you ;)

I am going to verify your change, but would you mind minifying your changes as well to fix the min.js version?

Thanks in advance!

**Comment by KTGLeiden** [comment]
I verified your change. If you would update the min.js file as well, I'll merge the PR ;)

**Comment by r03ert0** [comment]
cool! thank you @KTGLeiden :)
which tool did you use for minifying? I used uglify-js but my file is 11k whereas yours was 9k... (and I just added a few characters to the code :-/)

**Comment by KTGLeiden** [comment]
Good question @r03ert0  ;)

Well, it ís 4 years ago.. But I think I used https://javascript-minifier.com/.
I just ran it again, and it seems to match in size.

I think I'm going to update this repo a bit where I will make the minification a build step. Shouldn't be too hard nowadays :)

Thanks in advance!

**Comment by r03ert0** [comment]
there's a github action for that! (haven't tried it...) https://github.com/marketplace/actions/auto-minify

**Comment by r03ert0** [comment]
and thank you so much for writing this plugin!! it works like a charm <3 !!
I like the control panel very much. But now i'm trying to insert openseadragon in a shadow dom, and it's tricky to append the control panel there (it's a matter of not using `document` directly. I'll maybe leave it for a future PR :P)

**Comment by KTGLeiden** [comment]
Exactly, shouldnt be that hard :)

Op ma 1 jun. 2020 15:45 schreef Roberto Toro <notifications@github.com>:

**Comment by r03ert0** [comment]
I added the minified version :)

**Comment by KTGLeiden** [comment]
Perfect. Thanks again for letting me know and fixing it yourself ;)

**Pull request merged**
